// IAB Global Vendor List declaration text, bundled for every banner language.
//
// GENERATED — do not hand-edit. Regenerate with scripts/build-gvl.mjs, which reads
// the same GVL endpoint the live TCF runtime uses (see consent-manager
// utils/Tcfmanager.js) and rewrites this file:
//   node scripts/build-gvl.mjs
//
// Source: vendor list v176 (TCF policy vundefined), 2026-09-10T16:00:24Z.
//
// This half of the IAB banner text is NOT ours to write or translate: IAB owns the
// purpose, special-purpose, feature and special-feature declarations and publishes
// them per language. The live banner gets them through GVL.changeLanguage(); the
// preview reads this table so the two show identical wording.
//
// Why bundled rather than fetched (this is where the Webflow app differs from the
// Framer plugin, which fetches at runtime): a Designer Extension must declare every
// outbound origin in webflow.json, and the GVL host is not one of ours. Bundling
// keeps the preview to the origins already declared for review, and makes switching
// language instant and offline-proof. The cost is that this file has to be
// regenerated when IAB revises the list — the wording changes rarely, and a stale
// preview string never reaches a visitor: the live banner always fetches.
//
// Illustrations are deliberately dropped — the preview renders name + description
// only, matching the runtime banner's purpose accordions.
//
// Copy we author ourselves (section headings, toggle labels, the vendor-count line)
// lives in iabTranslations.js instead.

export const GVL_VENDOR_LIST_VERSION = 176;

export const GVL_DECLARATIONS = {
  en: {
    purposes: {
      1: { name: "Store and/or access information on a device", description: "Cookies, device or similar online identifiers (e.g. login-based identifiers, randomly assigned identifiers, network based identifiers) together with other information (e.g. browser type and information, language, screen size, supported technologies etc.) can be stored or read on your device to recognise it each time it connects to an app or to a website, for one or several of the purposes presented here." },
      2: { name: "Use limited data to select advertising", description: "Advertising presented to you on this service can be based on limited data, such as the website or app you are using, your non-precise location, your device type or which content you are (or have been) interacting with (for example, to limit the number of times an ad is presented to you)." },
      3: { name: "Create profiles for personalised advertising", description: "Information about your activity on this service (such as forms you submit, content you look at) can be stored and combined with other information about you (for example, information from your previous activity on this service and other websites or apps) or similar users. This is then used to build or improve a profile about you (that might include possible interests and personal aspects). Your profile can be used (also later) to present advertising that appears more relevant based on your possible interests by this and other entities." },
      4: { name: "Use profiles to select personalised advertising", description: "Advertising presented to you on this service can be based on your advertising profiles, which can reflect your activity on this service or other websites or apps (like the forms you submit, content you look at), possible interests and personal aspects." },
      5: { name: "Create profiles to personalise content", description: "Information about your activity on this service (for instance, forms you submit, non-advertising content you look at) can be stored and combined with other information about you (such as your previous activity on this service or other websites or apps) or similar users. This is then used to build or improve a profile about you (which might for example include possible interests and personal aspects). Your profile can be used (also later) to present content that appears more relevant based on your possible interests, such as by adapting the order in which content is shown to you, so that it is even easier for you to find content that matches your interests." },
      6: { name: "Use profiles to select personalised content", description: "Content presented to you on this service can be based on your content personalisation profiles, which can reflect your activity on this or other services (for instance, the forms you submit, content you look at), possible interests and personal aspects. This can for example be used to adapt the order in which content is shown to you, so that it is even easier for you to find (non-advertising) content that matches your interests." },
      7: { name: "Measure advertising performance", description: "Information regarding which advertising is presented to you and how you interact with it can be used to determine how well an advert has worked for you or other users and whether the goals of the advertising were reached. For instance, whether you saw an ad, whether you clicked on it, whether it led you to buy a product or visit a website, etc. This is very helpful to understand the relevance of advertising campaigns." },
      8: { name: "Measure content performance", description: "Information regarding which content is presented to you and how you interact with it can be used to determine whether the (non-advertising) content e.g. reached its intended audience and matched your interests. For instance, whether you read an article, watch a video, listen to a podcast or look at a product description, how long you spent on this service and the web pages you visit etc. This is very helpful to understand the relevance of (non-advertising) content that is shown to you." },
      9: { name: "Understand audiences through statistics or combinations of data from different sources", description: "Reports can be generated based on the combination of data sets (like user profiles, statistics, market research, analytics data) regarding your interactions and those of other users with advertising or (non-advertising) content to identify common characteristics (for instance, to determine which target audiences are more receptive to an ad campaign or to certain contents)." },
      10: { name: "Develop and improve services", description: "Information about your activity on this service, such as your interaction with ads or content, can be very helpful to improve products and services and to build new products and services based on user interactions, the type of audience, etc. This specific purpose does not include the development or improvement of user profiles and identifiers." },
      11: { name: "Use limited data to select content", description: "Content presented to you on this service can be based on limited data, such as the website or app you are using, your non-precise location, your device type, or which content you are (or have been) interacting with (for example, to limit the number of times a video or an article is presented to you)." },
    },
    specialPurposes: {
      1: { name: "Ensure security, prevent and detect fraud, and fix errors", description: "Your data can be used to monitor for and prevent unusual and possibly fraudulent activity (for example, regarding advertising, ad clicks by bots), and ensure systems and processes work properly and securely. It can also be used to correct any problems you, the publisher or the advertiser may encounter in the delivery of content and ads and in your interaction with them." },
      2: { name: "Deliver and present advertising and content", description: "Certain information (like an IP address or device capabilities) is used to ensure the technical compatibility of the content or advertising, and to facilitate the transmission of the content or ad to your device." },
      3: { name: "Save and communicate privacy choices", description: "The choices you make regarding the purposes and entities listed in this notice are saved and made available to those entities in the form of digital signals (such as a string of characters). This is necessary in order to enable both this service and those entities to respect such choices." },
    },
    features: {
      1: { name: "Match and combine data from other data sources", description: "Information about your activity on this service may be matched and combined with other information relating to you and originating from various sources (for instance your activity on a separate online service, your use of a loyalty card in-store, or your answers to a survey), in support of the purposes explained in this notice." },
      2: { name: "Link different devices", description: "In support of the purposes explained in this notice, your device might be considered as likely linked to other devices that belong to you or your household (for instance because you are logged in to the same service on both your phone and your computer, or because you may use the same Internet connection on both devices)." },
      3: { name: "Identify devices based on information transmitted automatically", description: "Your device might be distinguished from other devices based on information it automatically sends when accessing the Internet (for instance, the IP address of your Internet connection or the type of browser you are using) in support of the purposes exposed in this notice." },
    },
    specialFeatures: {
      1: { name: "Use precise geolocation data", description: "With your acceptance, your precise location (within a radius of less than 500 metres) may be used in support of the purposes explained in this notice." },
      2: { name: "Identify devices based on information actively requested", description: "With your acceptance, certain characteristics specific to your device might be requested and used to distinguish it from other devices (such as the installed fonts or plugins, the resolution of your screen) in support of the purposes explained in this notice." },
    },
  },
  nl: {
    purposes: {
      1: { name: "Informatie op een apparaat opslaan en/of openen", description: "Cookies, apparaat- of soortgelijke online-identificatoren (bijv. login-identificatiemiddelen, willekeurig toegewezen identificatiemiddelen, netwerk-gebaseerde identificatiemiddelen) samen met andere informatie (bijv. browsertype en informatie, taal, schermgrootte, ondersteunde technologieën enz.) kunnen op uw apparaat worden opgeslagen of gelezen om dat apparaat telkens wanneer het verbinding maakt met een app of met een website te herkennen, voor een of meer van de hier gepresenteerde doeleinden." },
      2: { name: "Beperkte gegevens gebruiken om advertenties te selecteren", description: "Advertenties die u op deze dienst worden aangeboden, kunnen gebaseerd zijn op beperkte gegevens, zoals de website of app die u gebruikt, uw niet-precieze locatie, uw apparaattype of welke content u gebruikt of hebt gebruikt (bijvoorbeeld om het aantal keren dat een advertentie aan u getoond wordt te beperken)." },
      3: { name: "Profielen aanmaken ten behoeve van gepersonaliseerde advertenties", description: "Informatie over uw activiteit op deze dienst (zoals formulieren die u indient, content die u bekijkt) kan worden opgeslagen en gecombineerd met andere informatie over u (bijvoorbeeld informatie uit uw eerdere activiteit op deze dienst en andere websites of apps) of soortgelijke gebruikers. Deze wordt vervolgens gebruikt om een profiel over u aan te maken of te verbeteren (met daarin bijvoorbeeld mogelijke interesses en persoonlijke aspecten). Uw profiel kan (ook later) door deze en andere rechtspersonen worden gebruikt om advertenties te tonen die relevanter lijken te zijn uitgaande van uw mogelijke interesses." },
      4: { name: "Profielen gebruiken voor de selectie van gepersonaliseerde advertenties", description: "Advertenties die u op deze dienst worden aangeboden, kunnen gebaseerd zijn op uw advertentieprofielen, die mogelijk uw activiteit op deze dienst of andere websites of apps (zoals de formulieren die u indient, content die u bekijkt), mogelijke interesses en/of persoonlijke aspecten weerspiegelen." },
      5: { name: "Profielen aanmaken ter personalisatie van content", description: "Informatie over uw activiteit op deze dienst (bijvoorbeeld formulieren die u indient, non-advertentiecontent die u bekijkt) kan worden opgeslagen en gecombineerd met andere gegevens over u (zoals uw eerdere activiteit op deze dienst of andere websites of apps) of soortgelijke gebruikers. Deze wordt vervolgens gebruikt om een profiel over u aan te maken of te verbeteren (met daarin bijvoorbeeld mogelijke interesses en persoonlijke aspecten). Uw profiel kan (ook later) worden gebruikt om content te tonen die relevanter lijkt te zijn uitgaande van uw mogelijke interesses, zoals door de volgorde aan te passen waarin content aan u wordt getoond, zodat het voor u nog gemakkelijker is om content te vinden die overeenkomt met uw interesses." },
      6: { name: "Profielen gebruiken ter selectie van gepersonaliseerde content", description: "Content die u op deze dienst wordt aangeboden, kan gebaseerd zijn op uw contentpersonalisatieprofielen, die mogelijk uw activiteit op deze of andere diensten (bijvoorbeeld de formulieren die u indient, content die u bekijkt), mogelijke interesses en/of persoonlijke aspecten weerspiegelen. Dit kan bijvoorbeeld worden gebruikt om de volgorde aan te passen waarin content aan u wordt getoond, zodat het voor u nog gemakkelijker is om (non-advertentie-) content te vinden die overeenkomt met uw interesses.”" },
      7: { name: "De prestaties van advertenties meten", description: "Informatie over welke advertentie er aan u wordt getoond en hoe u erop reageert, kan worden gebruikt om te bepalen hoe goed een advertentie in relatie tot u of andere gebruikers heeft gewerkt en of de doelen van de advertentie zijn bereikt. Bijvoorbeeld of u een advertentie hebt gezien, of u erop hebt geklikt, of de advertentie u ertoe heeft gebracht om een product te kopen of een website te bezoeken enz. Dit is zeer nuttig om de relevantie van reclamecampagnes in kaart te brengen." },
      8: { name: "Contentprestaties meten", description: "Informatie over welke content er aan u wordt gepresenteerd en hoe u erop reageert, kan worden gebruikt om te bepalen of de (non-advertentie)-content bijvoorbeeld het beoogde publiek heeft bereikt en met uw interesses overeenkomt. Bijvoorbeeld of u een artikel leest, een video bekijkt, naar een podcast luistert of een productbeschrijving bekijkt, hoeveel tijd u aan deze dienst hebt besteed en de webpagina’s die u bezoekt enz. Dit is zeer nuttig om de relevantie van (non-advertentie)-content in kaart te brengen. die aan u wordt getoond." },
      9: { name: "Publieksgroepen begrijpen aan de hand van statistieken of combinaties van gegevens uit verschillende bronnen", description: "Rapporten kunnen worden gegenereerd op basis van een combinatie van gegevenssets (zoals gebruikersprofielen, statistieken, marktonderzoek, analysegegevens) met betrekking tot uw interacties en die van andere gebruikers met advertenties of (non-advertentie)-content om gemeenschappelijke kenmerken te identificeren (bijvoorbeeld om te bepalen welke doelgroepen meer ontvankelijk zijn voor een advertentiecampagne of voor bepaalde content)." },
      10: { name: "Diensten ontwikkelen en verbeteren", description: "Informatie over uw activiteit op deze dienst, zoals uw interactie met advertenties of content, kan zeer nuttig zijn bij het verbeteren van producten en diensten en de creatie van nieuwe producten en diensten op basis van gebruikersinteracties, het type publiek enz. Dit specifieke doeleinde heeft geen betrekking op de ontwikkeling of verbetering van gebruikersprofielen en identificatoren." },
      11: { name: "Beperkte gegevens gebruiken om content te selecteren", description: "Content die u op deze dienst worden aangeboden, kan gebaseerd zijn op beperkte gegevens, zoals de website of app die u gebruikt, uw niet-precieze locatie, uw apparaattype of welke content u gebruikt of hebt gebruikt, (bijvoorbeeld om het aantal keren dat een video of artikel aan u getoond wordt te beperken)." },
    },
    specialPurposes: {
      1: { name: "Zorg dragen voor beveiliging, fraude voorkomen en detecteren en fouten opsporen", description: "Uw gegevens kunnen worden gebruikt om ongebruikelijke en mogelijk frauduleuze activiteiten te monitoren en te voorkomen (bijvoorbeeld, waar het gaat om advertenties, klikken op advertenties door bots) en ervoor te zorgen dat systemen en processen goed en veilig werken. Uw gegevens kunnen ook worden gebruikt om eventuele problemen te corrigeren die u, de uitgever of de adverteerder kunnen tegenkomen bij het leveren van content en advertenties en bij uw interactie met hen." },
      2: { name: "Advertenties en content leveren en tonen", description: "Bepaalde gegevens (zoals een IP-adres of de capaciteiten van een apparaat) worden gebruikt om de technische compatibiliteit van de content of advertenties te garanderen en om de overdracht van de content of advertentie naar uw apparaat te vergemakkelijken." },
      3: { name: "Privacykeuzes opslaan en delen", description: "De keuzes die u maakt met betrekking tot de doeleinden en organisaties die in dit bericht worden vermeld, worden opgeslagen en beschikbaar gesteld aan die organisaties in de vorm van digitale signalen (zoals een reeks tekens). Dit is nodig om zowel deze dienst als die organisaties in staat te stellen uw keuzes te respecteren." },
    },
    features: {
      1: { name: "Gegevens uit andere gegevensbronnen met elkaar matchen en combineren", description: "Informatie over uw activiteit op deze dienst kan worden gekoppeld en gecombineerd met andere informatie die op u betrekking heeft en afkomstig is uit verschillende bronnen (bijvoorbeeld uw activiteit op een afzonderlijke online dienst, uw gebruik van een klantenkaart in de winkel of uw antwoorden op een enquête), ter ondersteuning van de doeleinden die in deze kennisgeving worden uitgelegd." },
      2: { name: "Verschillende apparaten linken", description: "Ter ondersteuning van de doeleinden die in deze kennisgeving worden uitgelegd, kan uw apparaat worden beschouwd als waarschijnlijk gekoppeld aan andere apparaten die aan u of uw huishouden toebehoren (bijvoorbeeld omdat u bent ingelogd op dezelfde service op zowel uw telefoon als uw computer, of omdat u mogelijk dezelfde internetverbinding op beide apparaten gebruikt)." },
      3: { name: "Apparaten identificeren op basis van automatisch verzonden informatie", description: "Uw apparaat kan van andere apparaten worden onderscheiden op grond van informatie die het automatisch verzendt bij verkrijging van toegang tot het internet (bijvoorbeeld het IP-adres van uw internetverbinding of het type browser dat u gebruikt) ter ondersteuning van de doeleinden die in deze kennisgeving worden vermeld." },
    },
    specialFeatures: {
      1: { name: "Precieze geolocatiegegevens gebruiken", description: "Als u daarmee akkoord gaat, kan uw precieze locatie (binnen een straal van minder dan 500 meter) worden gebruikt ter ondersteuning van de doeleinden die in deze kennisgeving worden uitgelegd." },
      2: { name: "Apparaten identificeren op basis van actief opgevraagde informatie", description: "Als u daarmee akkoord gaat, kunnen bepaalde kenmerken die specifiek zijn voor uw apparaat worden opgevraagd en gebruikt om het van andere apparaten te onderscheiden (zoals de geïnstalleerde lettertypen of plug-ins, de resolutie van uw scherm) ter ondersteuning van de doeleinden die in deze kennisgeving worden uitgelegd." },
    },
  },
  fr: {
    purposes: {
      1: { name: "Stocker et/ou accéder à des informations sur un appareil", description: "Les cookies, appareils ou identifiants en ligne similaires (par ex. identifiants de connexion, identifiants assignés de façon aléatoire, identifiants réseau) ainsi que toutes autres informations (par ex. type et informations de navigateur, langue, taille d’écran, technologies prises en charge, etc.) peuvent être conservés ou lus sur votre appareil pour reconnaître celui-ci à chacune de ses connexions à une application ou à un site Web, pour une ou plusieurs des finalités présentées ici." },
      2: { name: "Utiliser des données limitées pour sélectionner la publicité", description: "La publicité qui vous est présentée sur ce service peut être basée sur des données limitées, telles que le site Web ou l’application que vous utilisez, votre emplacement approximatif, votre type d’appareil ou les contenus avec lesquels vous interagissez (ou avez interagi) (par exemple, pour limiter le nombre de fois où une publicité donnée vous est diffusée)." },
      3: { name: "Créer des profils pour la publicité personnalisée", description: "Les informations sur votre activité sur ce service (comme les formulaires que vous soumettez, les contenus que vous consultez) peuvent être conservées et conjuguées à d’autres informations vous concernant (par exemple, les informations de votre activité précédente sur ce service et d’autres sites Web ou applications) ou concernant des utilisateurs similaires. Ces informations servent ensuite à créer ou à améliorer un profil vous concernant (qui peut comporter d’éventuels centres d’intérêt et renseignements personnels). Votre profil peut être utilisé (également ultérieurement) pour présenter des publicités qui semblent plus pertinentes en fonction de vos centres d’intérêt éventuels par cette entité et d’autres entités." },
      4: { name: "Utiliser des profils pour sélectionner des publicités personnalisées", description: "La publicité qui vous est présentée sur ce service peut être basée sur vos profils publicitaires, qui peuvent être créés en fonction de votre activité sur ce service ou d’autres sites Web ou applications (comme les formulaires que vous soumettez, les contenus que vous consultez), ainsi que sur vos éventuels centres d’intérêt et renseignements personnels." },
      5: { name: "Créer des profils de contenus personnalisés", description: "Les informations concernant votre activité sur ce service (par exemple, les formulaires que vous soumettez, les contenus non publicitaires que vous consultez) peuvent être mémorisées et conjuguées à d’autres informations vous concernant (tels que les informations de votre activité précédente sur ce service ou d’autres sites Web ou applications) ou concernant des utilisateurs similaires. Ces informations servent ensuite à créer ou à améliorer un profil vous concernant (qui peut comporter, par exemple, d’éventuels centres d’intérêt et renseignements personnels). Votre profil peut servir (également à toute date ultérieure) à présenter des contenus qui semblent plus pertinents par rapport à vos éventuels centres d’intérêt, par exemple en adaptant l’ordre dans lequel les contenus vous sont présentés afin qu’il soit d’autant plus facile pour vous de trouver des contenus correspondant à vos centres d’intérêt." },
      6: { name: "Utiliser des profils pour sélectionner des contenus personnalisés", description: "Les contenus qui vous sont présentés sur ce service peuvent être basés sur vos profils de personnalisation de contenu qui peuvent correspondre à votre activité sur ce service ou d’autres services (par exemple, les formulaires que vous soumettez, le contenu que vous consultez, les éventuels centres d’intérêt et renseignements personnels). Cela peut par exemple être utilisé en adaptant l’ordre de présentation des contenus afin qu’il soit d’autant plus facile pour vous de trouver (sans publicité) des contenus correspondant à vos centres d’intérêt." },
      7: { name: "Mesurer la performance des publicités", description: "Les informations concernant la publicité qui vous est présentée et la manière dont vous interagissez avec elles peuvent être exploitées pour déterminer dans quelle mesure une publicité a été efficace pour vous ou d’autres utilisateurs et si les objectifs de la publicité ont été atteints. Par exemple, si vous avez vu une publicité, si vous avez cliqué dessus, si elle vous a conduit à acheter un produit ou à visiter un site Web, etc. Ces informations s’avèrent très utiles pour appréhender la pertinence des campagnes publicitaires." },
      8: { name: "Mesurer la performance des contenus", description: "Les informations concernant les contenus qui vous sont présentés et la manière dont vous interagissez avec ceux-ci peuvent servir à déterminer si des contenus (non publicitaires), par exemple, ont atteint leur public cible et correspondent à vos centres d’intérêt. Par exemple, si vous lisez un article, visionnez une vidéo, écoutez un podcast ou consultez une description de produit, combien de temps avez-vous passé sur ce service et les pages Web que vous visitez, etc. Ces informations s’avèrent très utiles pour comprendre la pertinence des contenus (non publicitaires) qui vous sont présentés." },
      9: { name: "Comprendre les publics par le biais de statistiques ou de combinaisons de données provenant de différentes sources", description: "Des rapports peuvent être générés en fonction de la combinaison d’ensembles de données (comme les profils d’utilisateurs, les statistiques, les études de marché, les données analytiques) concernant vos interactions et celles d’autres utilisateurs avec des contenus publicitaires ou (non publicitaires) afin d’identifier les caractéristiques communes (par exemple, pour déterminer quels publics cibles sont les plus réceptifs à une campagne publicitaire ou à certains contenus)." },
      10: { name: "Développer et améliorer les services", description: "Les informations sur votre activité sur ce service, telles que vos interactions avec des publicités ou du contenu, peuvent être très utiles pour améliorer les produits et services et pour créer de nouveaux produits et services en fonction des interactions des utilisateurs, du type d’audience, etc. Cette finalité spécifique n’inclut pas le développement ou l’amélioration des profils et des identifiants des utilisateurs." },
      11: { name: "Utiliser des données limitées pour sélectionner le contenu", description: "Le contenu qui vous est présenté sur ce service peut être basé sur des données limitées, telles que le site Web ou l’application que vous utilisez, votre emplacement non précis, votre type d’appareil ou le contenu avec lequel vous interagissez (ou avez interagi) (par exemple, pour limiter le nombre de diffusions d’une vidéo ou d’un article à votre attention)." },
    },
    specialPurposes: {
      1: { name: "Assurer la sécurité, prévenir et détecter la fraude et réparer les erreurs", description: "Vos données peuvent être utilisées pour surveiller et prévenir les activités inhabituelles et potentiellement frauduleuses (par exemple, en ce qui concerne la publicité, les clics publicitaires par des robots), et s’assurer que les systèmes et processus fonctionnent correctement et en toute sécurité. Elles peuvent également être utilisées pour corriger les problèmes que vous, l’éditeur ou l’annonceur pouvez rencontrer dans la diffusion de contenus et de publicités et dans votre interaction avec ceux-ci." },
      2: { name: "Fournir et présenter des publicités et du contenu", description: "Certaines informations (telles qu’une adresse IP ou des capacités d’appareil) sont utilisées pour assurer la compatibilité technique du contenu ou de la publicité, et pour faciliter la transmission du contenu ou de la publicité à votre appareil." },
      3: { name: "Enregistrer et communiquer les choix en matière de confidentialité", description: "Les choix que vous faites concernant les finalités et les entités énumérées dans le présent avis sont enregistrés et mis à la disposition de ces entités sous forme de signaux numériques (comme une chaîne de caractères). Cela est nécessaire pour permettre à la fois à ce service et à ces entités de respecter ces choix." },
    },
    features: {
      1: { name: "Mettre en correspondance et combiner des données à partir d’autres sources de données", description: "Les informations concernant votre activité sur ce service peuvent être associées et combinées à d’autres informations vous concernant et provenant de diverses sources (par exemple, votre activité sur un service en ligne distinct, votre utilisation d’une carte de fidélité en magasin ou vos réponses à une enquête), à l’appui des finalités expliquées dans le présent avis." },
      2: { name: "Relier différents appareils", description: "À l’appui des finalités expliquées dans le présent avis, votre appareil pourrait être considéré comme probablement lié à d’autres appareils qui vous appartiennent ou appartiennent à votre foyer (par exemple, parce que vous êtes connecté(e) au même service sur votre téléphone et votre ordinateur, ou parce que vous pouvez utiliser la même connexion Internet sur les deux appareils)." },
      3: { name: "Identifier les appareils en fonction des informations transmises automatiquement", description: "Votre appareil peut se distinguer d’autres appareils en fonction des informations qu’il envoie automatiquement lors de l’accès à Internet (par exemple, l’adresse IP de votre connexion Internet ou le type de navigateur utilisé) à l’appui des finalités exposées dans le présent avis." },
    },
    specialFeatures: {
      1: { name: "Utiliser des données de géolocalisation précises", description: "Avec votre acceptation, votre emplacement précis (dans un rayon inférieur à 500 mètres) peut être utilisé à l’appui des finalités expliquées dans le présent avis." },
      2: { name: "Identifier les appareils à partir des informations demandées explicitement", description: "Avec votre acceptation, certaines caractéristiques spécifiques à votre appareil peuvent être demandées et utilisées pour le distinguer d’autres appareils (comme les polices ou plug-ins installés, la résolution de votre écran) à l’appui des finalités expliquées dans le présent avis." },
    },
  },
  de: {
    purposes: {
      1: { name: "Speichern von oder Zugriff auf Informationen auf einem Endgerät", description: "Cookies, Endgeräte- oder ähnliche Online-Kennungen (z. B. login-basierte Kennungen, zufällig generierte Kennungen, netzwerkbasierte Kennungen) können zusammen mit anderen Informationen (z. B. Browsertyp und Browserinformationen, Sprache, Bildschirmgröße, unterstützte Technologien usw.) auf Ihrem Endgerät gespeichert oder von dort ausgelesen werden, um es jedes Mal wiederzuerkennen, wenn es eine App oder einer Webseite aufruft. Dies geschieht für einen oder mehrere der hier aufgeführten Verarbeitungszwecke." },
      2: { name: "Verwendung reduzierter Daten zur Auswahl von Werbeanzeigen", description: "Werbeanzeigen, die Ihnen auf diesem Dienst präsentiert werden, können auf reduzierten Daten basieren, wie z. B. der Webseite oder App, die Sie gerade verwenden, Ihrem ungefähren Standort, Ihrem Gerätetyp oder den Inhalten, mit denen Sie interagieren (oder interagiert haben) (z. B., um die Anzeigefrequenz der Werbung zu begrenzen, die Ihnen ausgespielt werden)." },
      3: { name: "Erstellung von Profilen für personalisierte Werbung", description: "Informationen über Ihre Aktivitäten auf diesem Dienst (wie ausgefüllte Formulare, angesehene Inhalte) können gespeichert und mit anderen Informationen über Sie (z. B. Informationen aus Ihrer vorherigen Aktivität auf diesem Dienst oder anderen Webseiten oder Apps) oder ähnlichen Benutzern kombiniert werden. Diese werden dann verwendet, um ein Profil über Sie zu erstellen oder zu verbessern (dies kann z. B. mögliche Interessen und persönliche Merkmale beinhalten). Ihr Profil kann (auch zu einem späteren Zeitpunkt) verwendet werden, um es zu ermöglichen, Ihnen Werbung zu präsentieren, die aufgrund Ihrer möglichen Interessen für Sie wahrscheinlich relevanter ist." },
      4: { name: "Verwendung von Profilen zur Auswahl personalisierter Werbung", description: "Werbung, die Ihnen auf diesem Dienst angezeigt wird, kann auf Ihrem Werbeprofil basieren.  Dieses Werbeprofil kann Ihre Aktivitäten (wie ausgefüllte Formulare, angesehene Inhalte) auf diesem Dienst oder anderen Webseiten oder Apps, mögliche Interessen und persönliche Merkmale beinhalten." },
      5: { name: "Erstellung von Profilen zur Personalisierung von Inhalten", description: "Informationen über Ihre Aktivitäten auf diesem Dienst (wie zum Beispiel: ausgefüllte Formulare, angesehene nicht werbliche Inhalte) können gespeichert und mit anderen Informationen über Sie (wie Ihrer vorherigen Aktivität auf diesem Dienst oder anderen Webseiten oder Apps) oder ähnlichen Benutzern kombiniert werden.Diese werden dann verwendet, um ein Profil über Sie zu erstellen oder zu ergänzen (dies kann z.B. mögliche Interessen und persönliche Merkmale beinhalten). Ihr Profil kann (auch zu einem späteren Zeitpunkt) verwendet werden, um Ihnen Inhalte anzuzeigen, die aufgrund Ihrer möglichen Interessen für Sie wahrscheinlich relevanter sind, indem z. B. die Reihenfolge, in der Ihnen Inhalte angezeigt werden, geändert wird, um es Ihnen noch leichter zu machen, Inhalte zu finden, die Ihren Interessen entsprechen." },
      6: { name: "Verwendung von Profilen zur Auswahl personalisierter Inhalte", description: "Inhalte, die Ihnen auf diesem Dienst präsentiert werden, können auf Ihren Inhaltsprofilen basieren, die Ihre Aktivitäten auf diesem oder anderen Diensten (wie Formulare, die Sie einreichen, Inhalte, die Sie sich ansehen), mögliche Interessen und persönliche Aspekte widerspiegeln können. Dies kann beispielsweise dazu genutzt werden, um die Reihenfolge anzupassen, in der Ihnen Inhalte angezeigt werden, um es Ihnen noch leichter zu machen, (Nicht-Werbe-)Inhalte zu finden, die Ihren Interessen entsprechen." },
      7: { name: "Messung der Werbeleistung", description: "Informationen darüber, welche Werbung Ihnen präsentiert wird und wie Sie damit interagieren, können verwendet werden, um festzustellen, wie sehr eine Werbung Sie oder andere Benutzer angesprochen hat und ob die Ziele der Werbekampagne erreicht wurden. Die Informationen umfassen zum Beispiel, ob Sie sich eine Anzeige angesehen haben, ob Sie daraufgeklickt haben, ob sie Sie dazu animiert hat, ein Produkt zu kaufen oder eine Webseite zu besuchen usw. Diese Informationen sind hilfreich, um die Relevanz von Werbekampagnen zu ermitteln." },
      8: { name: "Messung der Performance von Inhalten", description: "Informationen darüber, welche Werbung Ihnen präsentiert wird und wie Sie damit interagieren, können dazu verwendet werden festzustellen, ob (nicht werbliche) Inhalte z. B. die beabsichtigte Zielgruppe erreicht und Ihren Interessen entsprochen haben. Dazu gehören beispielsweise Informationen darüber, ob Sie einen bestimmten Artikel gelesen, sich ein bestimmtes Video angesehen, einen bestimmten Podcast angehört oder sich eine bestimmte Produktbeschreibung angesehen haben, wie viel Zeit Sie auf diesem Dienst und den von Ihnen besuchten Webseiten verbracht haben usw. Diese Informationen helfen dabei, die Relevanz von (nicht werblichen) Inhalten, die Ihnen angezeigt werden, zu ermitteln." },
      9: { name: "Analyse von Zielgruppen durch Statistiken oder Kombinationen von Daten aus verschiedenen Quellen", description: "Basierend auf der Kombination von Datensätzen (wie Benutzerprofilen, Statistiken, Marktforschung, Analysedaten) können Berichte über Ihre Interaktionen und die anderer Benutzer mit Werbe- oder (nicht werblichen) Inhalten erstellt werden, um gemeinsame Merkmale zu ermitteln (z. B., um festzustellen, welche Zielgruppen für eine Werbekampagne oder für bestimmte Inhalte empfänglich sind)." },
      10: { name: "Entwicklung und Verbesserung der Angebote", description: "Informationen über Ihre Aktivitäten auf diesem Angebot, wie z. B. Ihre Interaktion mit Anzeigen oder Inhalten, können dabei helfen, Produkte und Angebote zu verbessern und neue Produkte und Angebote zu entwickeln basierend auf Benutzerinteraktionen, der Art der Zielgruppe usw. Dieser Verarbeitungszweck umfasst nicht die Entwicklung, Ergänzung oder Verbesserung von Benutzerprofilen und Kennungen." },
      11: { name: "Verwendung reduzierter Daten zur Auswahl von Inhalten", description: "Inhalte, die Ihnen auf diesem Dienst präsentiert werden, können auf reduzierten Daten basieren, wie z. B. der Webseite oder App, die Sie verwenden, Ihrem ungefähren Standort, Ihrem Endgerätetyp oder der Information, mit welchen Inhalten Sie interagieren (oder interagiert haben) (z. B. zur Begrenzung wie häufig Ihnen ein Video oder ein Artikel angezeigt wird)." },
    },
    specialPurposes: {
      1: { name: "Gewährleistung der Sicherheit, Verhinderung und Aufdeckung von Betrug und Fehlerbehebung", description: "Ihre Daten können verwendet werden, um ungewöhnliche und potenziell betrügerische Aktivitäten (zum Beispiel bezüglich Werbung, Werbe-Klicks durch Bots) zu überwachen und zu verhindern, und um sicherzustellen, dass Systeme und Prozesse ordnungsgemäß und sicher funktionieren. Die Daten können auch verwendet werden, um Probleme zu beheben, die Sie, der Webseite- oder Appbetreiber oder der Werbetreibende bei der Bereitstellung von Inhalten und Anzeigen und bei Ihrer Interaktion mit diesen haben können." },
      2: { name: "Bereitstellung und Anzeige von Werbung und Inhalten", description: "Bestimmte Informationen (wie IP-Adresse oder Endgerätefunktionen) werden verwendet, um die technische Kompatibilität des Inhalts oder der Werbung zu gewährleisten und die Übertragung des Inhalts oder der Werbung auf Ihr Endgerät zu ermöglichen." },
      3: { name: "Ihre Entscheidungen zum Datenschutz speichern und übermitteln", description: "Die von Ihnen in Bezug auf die in diesem Hinweis aufgeführten Zwecke und Unternehmen getroffenen Entscheidungen werden gespeichert und den betreffenden Unternehmen in Form digitaler Signale (z. B. einer Zeichenfolge) zur Verfügung gestellt. Nur so können sowohl dieser Dienst als auch die betreffenden Unternehmen die jeweiligen Entscheidungen respektieren." },
    },
    features: {
      1: { name: "Abgleichung und Kombination von Daten aus unterschiedlichen Quellen", description: "Informationen über Ihre Aktivitäten auf diesem Dienst können zur Unterstützung der in diesem Rahmenwerk erläuterten Zwecke mit anderen Informationen über Sie aus unterschiedlichen Quellen abgeglichen und kombiniert werden (z. B. Ihre Aktivitäten auf einem anderen Online-Dienst, Ihrer Nutzung einer Kundenkarte im Geschäft oder Ihren Antworten auf eine Umfrage)." },
      2: { name: "Verknüpfung verschiedener Endgeräte", description: "Zur Unterstützung der in diesem Rahmenwerk erläuterten Zwecke kann ermittelt werden, ob es wahrscheinlich ist, dass Ihr Endgerät mit anderen Endgeräten verbunden ist, die Ihnen oder Ihrem Haushalt angehören (z. B., weil Sie sowohl auf Ihrem Handy als auch auf Ihrem Computer beim gleichen Dienst angemeldet sind oder weil Sie auf beiden Endgeräten die gleiche Internetverbindung verwenden)." },
      3: { name: "Identifikation von Endgeräten anhand automatisch übermittelter Informationen", description: "Ihr Endgerät kann zur Unterstützung der in diesem Rahmenwerk erläuterten Zwecke mithilfe von Informationen unterschieden werden, die es beim Zugriff auf das Internet automatisch übermittelt (z. B. die IP-Adresse Ihrer Internetverbindung oder die Art des Browsers, den Sie verwenden)." },
    },
    specialFeatures: {
      1: { name: "Verwendung genauer Standortdaten", description: "Mit Ihrer Zustimmung kann Ihr genauer Standort (mit einem Radius von weniger als 500 Metern) zur Unterstützung der in diesem Rahmenwerk erläuterten Zwecke verwendet werden." },
      2: { name: "Geräte anhand von aktiv angeforderten Informationen identifizieren", description: "Mit Ihrer Zustimmung können bestimmte für Ihr Endgerät spezifische Merkmale angefordert und verwendet werden, um es von anderen Endgeräten zu unterscheiden (wie z. B. die installierten Zeichensätze oder Plugins, die Auflösung Ihres Bildschirms), um die in diesem Rahmenwerk erläuterten Zwecke zu unterstützen." },
    },
  },
  it: {
    purposes: {
      1: { name: "Archiviare informazioni su dispositivo e/o accedervi", description: "Cookie, identificatori del dispositivo o analoghi identificatori online (ad es. identificatori basati sull’accesso, identificatori assegnati casualmente, identificatori basati sulla rete) insieme ad altre informazioni (ad es. tipo di browser e informazioni sul browser, lingua, dimensioni dello schermo, tecnologie supportate, ecc.) possono essere archiviati sul o letti dal dispositivo dell’utente per riconoscerlo ogni volta che l’utente si connette a un’app o a un sito web, per una o più finalità qui presentate." },
      2: { name: "Utilizzare dati limitati per la selezione della pubblicità", description: "La pubblicità presentata all’utente su questo servizio può basarsi su dati limitati, come il sito web o l’app in uso, la posizione approssimativa, il tipo di dispositivo dell’utente o il contenuto con cui interagisce (o ha interagito) (ad esempio, per limitare il numero di volte in cui un annuncio viene presentato all’utente)." },
      3: { name: "Creare profili per la pubblicità personalizzata", description: "Le informazioni sull’attività dell’utente su questo servizio (come i moduli inviati, i contenuti visualizzati) possono essere archiviate e combinate con altre informazioni riguardanti l’utente (ad esempio, informazioni tratte dall’attività precedente dell’utente sul servizio e su altri siti web o app) o utenti simili. Tali informazioni vengono, quindi, impiegate per creare o migliorare un profilo dell’utente (che potrebbe includere eventuali interessi e aspetti personali). Questa o altre entità potrebbero avvalersi del profilo dell’utente (anche in seguito) per presentare annunci più pertinenti sulla base dei possibili interessi dell’utente." },
      4: { name: "Utilizzare profili per la selezione di pubblicità personalizzata", description: "La pubblicità presentata all’utente sul servizio può basarsi sui suoi profili pubblicitari, che possono riflettere l’attività sul servizio o su altri siti web o app (come i moduli inviati, i contenuti visualizzati), possibili interessi e aspetti personali dell’utente." },
      5: { name: "Creare profili per la personalizzazione dei contenuti", description: "Le informazioni sull’attività dell’utente sul questo servizio (ad esempio, i moduli inviati, i contenuti non pubblicitari visualizzati) possono essere archiviate e combinate con altre informazioni riguardanti l’utente (quali informazioni tratte dall’attività precedente dell’utente sul servizio o su altri siti web o app) o utenti simili. Tali informazioni vengono, quindi, impiegate per creare o migliorare un profilo dell’utente (il che potrebbe includere, ad esempio, possibili interessi e aspetti personali). Il profilo dell’utente può essere utilizzato (anche successivamente) per presentare contenuti che, a giudicare dai possibili interessi dell’utente, appaiono più pertinenti, ad esempio adattando l’ordine in cui i contenuti vengono mostrati, in modo da rendere ancora più facile per l’utente trovare contenuti che rispondano ai suoi interessi." },
      6: { name: "Utilizzare profili per la selezione di contenuti personalizzati", description: "I contenuti presentati all’utente sul servizio possono basarsi sui suoi profili per la personalizzazione dei contenuti, che possono riflettere la sua attività su questo o altri servizi (ad esempio, i moduli inviati, i contenuti visualizzati), eventuali interessi e aspetti personali. Ciò può essere utilizzato, ad esempio, per adattare l’ordine in cui i contenuti vengono mostrati all’utente, in modo da rendere ancora più facile per l’utente trovare contenuti (non pubblicitari) che rispondano ai suoi interessi." },
      7: { name: "Misurare le prestazioni degli annunci", description: "Le informazioni relative alla pubblicità presentata all’utente e al modo in cui l’utente interagisce con essa possono essere utilizzate per determinare il livello di efficacia di una pubblicità riguardo all’utente o ad altri utenti e se gli obiettivi della pubblicità sono stati raggiunti. Ad esempio, se l’utente ha visualizzato un annuncio, vi ha cliccato sopra, ha indotto l’utente ad acquistare un prodotto o a visitare un sito web, ecc. Ciò è molto utile per comprendere la pertinenza delle campagne pubblicitarie." },
      8: { name: "Misurare le prestazioni dei contenuti", description: "Le informazioni relative ai contenuti presentati all’utente e al modo in cui l’utente interagisce con essi possono essere utilizzate per stabilire se i contenuti (non pubblicitari) hanno raggiunto, ad es., il pubblico previsto e incontrato i suoi interessi. Ad esempio, se l’utente legge un articolo, guarda un video, ascolta un podcast o guarda la descrizione di un prodotto, quanto tempo trascorre sul servizio, le pagine web visitate, ecc. Ciò è molto utile per comprendere la pertinenza dei contenuti (non pubblicitari) che vengono mostrati all’utente." },
      9: { name: "Comprendere il pubblico attraverso statistiche o la combinazione di dati provenienti da fonti diverse", description: "I report possono essere generati in base alla combinazione di set di dati (come profili utente, statistiche, ricerche di mercato, dati analitici) riguardanti le interazioni dell’utente e quelle di altri utenti con contenuti pubblicitari o (non pubblicitari) al fine di identificare caratteristiche comuni (ad esempio, per determinare quale pubblico di riferimento è più ricettivo a una campagna pubblicitaria o a determinati contenuti)." },
      10: { name: "Sviluppare e migliorare i servizi", description: "Le informazioni sull’attività dell’utente sul servizio, come l’interazione con annunci o contenuti, possono essere molto utili per migliorare prodotti e servizi e creare nuovi prodotti e servizi basati sulle interazioni dell’utente, il tipo di pubblico, ecc. Questa specifica finalità non include lo sviluppo o il miglioramento dei profili utente e degli identificatori." },
      11: { name: "Utilizzare dati limitati per la selezione dei contenuti", description: "I contenuti presentati all’utente sul servizio possono basarsi su dati limitati, come il sito web o l’app in uso, la posizione approssimativa, il tipo di dispositivo dell’utente o il contenuto con cui interagisce (o ha interagito) (ad esempio, per limitare il numero di volte in cui un video o un articolo viene presentato all’utente)." },
    },
    specialPurposes: {
      1: { name: "Garantire la sicurezza, prevenire e rilevare frodi, correggere errori", description: "I dati dell’utente possono essere utilizzati per monitorare e prevenire attività  insolite e potenzialmente fraudolente (ad esempio, con riguardo alla pubblicità, i click sugli annunci da parte di bot) e garantire che i sistemi e i processi funzionino correttamente e in modo sicuro. Possono anche essere utilizzati per correggere eventuali problemi riscontrati dall’utente, dall’editore o dall’inserzionista nella erogazione di contenutio e annunci e nell’interazione dell’utente con essi." },
      2: { name: "Erogare e presentare pubblicità e contenuto", description: "Alcune informazioni (come un indirizzo IP o le funzionalità del dispositivo) vengono utilizzate per garantire la compatibilità tecnica del contenuto o dell'annuncio e per facilitare la trasmissione del contenuto o dell’annuncio al dispositivo dell’utente." },
      3: { name: "Salvare e comunicare le scelte sulla privacy", description: "Le scelte effettuate dall'utente in merito alle finalità e alle entità elencate nella presente informativa vengono salvate e messe a disposizione di tali entità sotto forma di segnali digitali (come ad esempio una stringa di caratteri). Ciò è necessario per consentire sia a questo servizio che a tali entità di rispettare tali scelte." },
    },
    features: {
      1: { name: "Abbinare e combinare dati provenienti da altre fonti di dati", description: "Le informazioni sull’attività dell’utente sul servizio possono essere abbinate e combinate con altre informazioni sull’utente provenienti da varie fonti (ad esempio, l’attività dell’utente su un'altro servizio online, l’uso di una carta fedeltà in negozio o le risposte dell’utente a un sondaggio), a supporto delle finalità illustrate nella presente informativa." },
      2: { name: "Collegare diversi dispositivi", description: "A supporto delle finalità illustrate nella presente informativa, il dispositivo dell’utente potrebbe considerarsi collegato, con tutta probabilità, ad altri dispositivi appartenenti all’utente o alla sua famiglia (ad esempio, perché l’utente ha effettuato l’accesso a un medesimo servizio sia da telefono sia da computer o perché usa la stessa connessione Internet su entrambi i dispositivi)." },
      3: { name: "Identificare i dispositivi in base alle informazioni trasmesse automaticamente", description: "Il dispositivo dell’utente potrebbe essere riconosciuto tra altri dispositivi in base alle informazioni che invia automaticamente quando accede a Internet (ad esempio, l’indirizzo IP della connessione Internet o il tipo di browser utilizzato) a supporto delle finalità esposte nella presente informativa." },
    },
    specialFeatures: {
      1: { name: "Utilizzare dati di geolocalizzazione precisi", description: "Con il consenso dell’utente, la sua posizione precisa (entro un raggio inferiore a 500 metri) può essere utilizzata a supporto delle finalità illustrate nella presente informativa." },
      2: { name: "Riconoscere i dispositivi in base a informazioni richieste attivamente", description: "In presenza del consenso dell’utente potrebbero essere richieste ed essere utilizzate alcune caratteristiche specifiche del suo dispositivo per distinguerlo da altri dispositivi (come i font o i plug-in installati, la risoluzione dello schermo) a supporto delle finalità illustrate nella presente informativa." },
    },
  },
  pl: {
    purposes: {
      1: { name: "Przechowywanie informacji na urządzeniu lub dostęp do nich", description: "Pliki cookie, identyfikatory urządzeń lub podobne identyfikatory online (np. identyfikatory oparte na logowaniu, identyfikatory przypisywane losowo, identyfikatory sieciowe) w połączeniu z innymi informacjami (takimi jak rodzaj przeglądarki i informacje w niej zawarte, język, rozmiar ekranu, obsługiwane technologie itp.) mogą być przechowywane lub odczytywane na Twoim urządzeniu celem rozpoznania urządzenia za każdym razem, gdy następuje połączenie z aplikacją lub witryną internetową – w celach tutaj przedstawionych." },
      2: { name: "Wykorzystywanie ograniczonych danych do wyboru reklam", description: "Reklamy prezentowane Tobie w serwisie mogą opierać się na ograniczonych danych takich jak witryna internetowa lub aplikacja, z których korzystasz, Twoja nieprecyzyjna lokalizacja, rodzaj urządzenia albo treści przeglądane przez Ciebie (na przykład w celu ograniczenia liczby wyświetleń danej reklamy)." },
      3: { name: "Tworzenie profili w celu spersonalizowanych reklam", description: "Informacje na temat Twojej aktywności w serwisie (np. przesyłane formularze, przeglądane treści) mogą być przechowywane i łączone z innymi informacjami dotyczącymi Ciebie (na przykład informacjami o Twojej poprzedniej aktywności w serwisie, innych witrynach internetowych lub aplikacjach) lub podobnych osób. Informacje te wykorzystuje się następnie do tworzenia lub ulepszania profilu odnoszącego się do Ciebie (który to profil może na przykład obejmować Twoje zainteresowania i cechy osobiste). Twój profil może być wykorzystywany (również później) do pokazywania reklam, które wydają się bardziej odpowiednie, biorąc pod uwagę Twoje możliwe zainteresowania." },
      4: { name: "Wykorzystanie profili do wyboru spersonalizowanych reklam", description: "Reklamy, ktore są Ci prezentowane w tym serwisie mogą być oparta na Twoich profilach reklamowych, które mogą odzwierciedlać Twoją aktywność w serwisie, innych witrynach internetowych lub aplikacjach (np. przesyłane formularze, przeglądane treści), możliwe zainteresowania i cechy osobiste." },
      5: { name: "Tworzenie profili w celu personalizacji treści", description: "Informacje na temat Twojej aktywności w serwisie (np. przesyłane formularze, przeglądane treści niezwiązane z reklamami) mogą być przechowywane i łączone z innymi informacjami dotyczącymi Ciebie (na przykład informacjami o Twojej poprzedniej aktywności w usłudze, innych witrynach internetowych lub aplikacjach) lub podobnych osób. Informacje te wykorzystuje się następnie do tworzenia lub ulepszania Twojego profilu (który to profil może obejmować możliwe zainteresowania i cechy osobiste). Twój profil może być wykorzystywany (również później) do prezentowania treści, które wydają się bardziej odpowiednie w oparciu o Twoje ewentualne zainteresowania, na przykład poprzez dostosowanie kolejności wyświetlania treści, aby jeszcze łatwiej było Ci znaleźć treści odpowiadające Twoim zainteresowaniom." },
      6: { name: "Wykorzystywanie profili w celu doboru spersonalizowanych treści", description: "Treści prezentowane w serwisie mogą być oparte na Twoich profilach spersonalizowanej treści, które mogą odzwierciedlać Twoją aktywność w tym lub innym serwisie (bierze się pod uwagę przesyłane formularze, przeglądane treści itd.), możliwe zainteresowania i aspekty osobiste. Informacje te mogą zostać wykorzystane na przykład do dostosowania kolejności wyświetlania treści, aby jeszcze bardziej ułatwić Ci przeglądanie właściwych (niereklamowych) treści odpowiadających Twoim zainteresowaniom." },
      7: { name: "Pomiar efektywności reklam", description: "Informacje dotyczące tego, które reklamy są Ci pokazywane, jak również tego, jak na nie reagujesz, mogą pomóc określić, na ile dobrze zadziałała dana reklama na Ciebie lub inne osoby i czy cele reklamy zostały osiągnięte. Na przykład czy w ogóle widziałeś reklamę, czy ją na nią kliknąłeś, czy skłoniła to Ciebie do zakupu produktu lub odwiedzenia witryny internetowej itp. Jest to bardzo pomocne w zrozumieniu  znaczenia kampanii reklamowych." },
      8: { name: "Pomiar efektywności treści", description: "Informacje dotyczące prezentowanych Ci treści oraz Twoje reakcje na nie mogą zostać wykorzystane do określenia, czy (niereklamowe) treści dotarły – na przykład – do zamierzonych odbiorców i czy odpowiadały Twoim zainteresowaniom. Pozwalają się dowiedzieć, czy przeczytałeś artykuł, obejrzałeś film, słuchałeś podcastu lub sprawdziłeś opis produktu, ile czasu spędziłeś, korzystając z serwisu, jakie witryny internetowe odwiedziłeś itp. Pomaga to poznać znaczenie (niereklamowych) pokazywanych Tobie treści." },
      9: { name: "Rozumienie odbiorców dzięki statystyce lub kombinacji danych z różnych źródeł", description: "Można generować raporty na podstawie kombinacji zestawów danych (takich jak profile użytkowników, statystyki, badania rynku, dane analityczne) dotyczących reakcji użytkowników na treści reklamowe lub niereklamowe. Chodzi o identyfikację wspólnych cech (na przykład określenie, którzy odbiorcy docelowi są bardziej otwarci na kampanię reklamową lub treści danego typu)." },
      10: { name: "Rozwój i ulepszanie usług", description: "Informacje na temat Twojej aktywności w serwisie, np. odnoszące się do Twoich reakcji na reklamy lub treści, mogą być bardzo pomocne w ulepszaniu produktów i usług oraz tworzeniu nowych produktów i usług w oparciu o Twoje interakcje, typ odbiorców itp. Ten konkretny cel nie obejmuje tworzenia ani ulepszania profili czy identyfikatorów użytkowników." },
      11: { name: "Wykorzystywanie ograniczonych danych do wyboru treści", description: "Treści prezentowane Tobie w serwisie mogą opierać się na ograniczonych danych takich jak witryna internetowa lub aplikacja, z których korzystasz, Twoja nieprecyzyjna lokalizacja, rodzaj urządzenia albo treści przeglądane przez Ciebie (na przykład w celu ograniczenia liczby wyświetleń danego filmu lub artykułu)." },
    },
    specialPurposes: {
      1: { name: "Zapewnienie bezpieczeństwa, zapobieganie oszustwom i naprawianie błędów", description: "Twoje dane mogą być wykorzystywane do monitorowania i zapobiegania oszustwom (np. w odniesieniu do reklam i ich klikania przez boty) oraz zapewnienia prawidłowego i bezpiecznego działania systemów i procesów. Dane te mogą być również wykorzystywane do korygowania wszelkich problemów, jakie mogą wystąpić u Ciebie, wydawcy lub reklamodawcy w związku z dostarczaniem treści i reklam oraz w związku z Twoją interakcją z treścią i reklamami." },
      2: { name: "Dostarczanie i prezentowanie reklam i treści", description: "Niektóre informacje (np. adres IP lub funkcje urządzenia) są wykorzystywane w celu zapewnienia technicznej zgodności treści lub reklam lub w celu ułatwienia przesyłania treści lub reklam do Twojego urządzenia." },
      3: { name: "Zapisanie decyzji dotyczących prywatności oraz informowanie o nich", description: "Decyzje podejmowane przez użytkownika dotyczące celów i podmiotów wymienionych w niniejszym powiadomieniu są zapisane i udostępniane tym podmiotom w formie sygnałów cyfrowych (np. ciągu znaków). Jest to konieczne dla zapewnienia aby te podmioty i usługi respektowały podjęte przez użytkownika decyzje." },
    },
    features: {
      1: { name: "Dopasowanie i łączenie danych z innych źródeł", description: "Informacje dotyczące aktywności użytkownika w usłudze mogą być łączone z innymi informacjami dotyczącymi użytkownika, pochodzącymi z różnych źródeł takich jak aktywność w innej usłudze online, korzystanie z karty lojalnościowej w sklepie lub odpowiedzi na pytania w ankiecie – w celach wyjaśnionych w niniejszym powiadomieniu." },
      2: { name: "Łączenie różnych urządzeń", description: "W związku z celami opisanymi w niniejszym powiadomieniu można przypuszczać, że urządzenie użytkownika jest powiązane z innymi urządzeniami, które należą do użytkownika lub znajdują się w jego gospodarstwie domowym (na przykład gdy użytkownik loguje się do tej samej usługi zarówno na telefonie, jak i komputerze, ewentualnie korzysta z tego samego połączenia internetowego na obu urządzeniach)." },
      3: { name: "Identyfikacja urządzeń na podstawie informacji przesyłanych automatycznie", description: "Urządzenie użytkownika może odróżniać się od innych urządzeń na podstawie informacji, które automatycznie wysyła, uzyskując dostęp do internetu (na przykład na podstawie adresu IP połączenia internetowego lub rodzaju wykorzystywanej przeglądarki) – w celach określonych w niniejszym powiadomieniu." },
    },
    specialFeatures: {
      1: { name: "Użycie dokładnych danych geolokalizacyjnych", description: "Za zgodą użytkownika do realizacji celów określonych w niniejszym powiadomieniu można wykorzystywać dokładną lokalizację użytkownika (mowa tu o promieniu nieprzekraczającym 500 metrów)." },
      2: { name: "Identyfikowanie urządzeń na podstawie aktywnie żądanych informacji", description: "Za zgodą użytkownika może zostać wysłane żądanie o podanie określonych cech urządzenia użytkownika, które pozwolą na odróżnienie go od innych urządzeń (np. zainstalowane wtyczki i czcionki, rozdzielczość ekranu) – w związku z realizacją celów, o których mowa w niniejszym powiadomieniu." },
    },
  },
  pt: {
    purposes: {
      1: { name: "Armazenar e/ou aceder a informações num dispositivo", description: "Cookies, identificadores de dispositivos ou identificadores online semelhantes (por exemplo, identificadores baseados em início de sessão, identificadores atribuídos aleatoriamente, identificadores baseados na rede) juntamente com outras informações (por exemplo, tipo de navegador e informações, idioma, tamanho do ecrã, tecnologias suportadas, etc.) podem ser armazenados ou lidos no seu dispositivo para reconhecê-lo sempre que se ligar a uma aplicação ou a um site, para uma ou várias das finalidades aqui apresentadas." },
      2: { name: "Utilizar dados limitados para selecionar publicidade", description: "A publicidade que lhe é apresentada neste serviço pode basear-se em dados limitados, tais como o site ou a aplicação que está a utilizar, a sua localização não precisa, o seu tipo de dispositivo ou o conteúdo com que está (ou esteve) a interagir (por exemplo, para limitar o número de vezes que um anúncio lhe é apresentado)." },
      3: { name: "Criar perfis para publicidade personalizada", description: "As informações sobre a sua atividade neste serviço (tais como formulários que envia, conteúdos que visualiza) podem ser armazenadas e combinadas com outras informações sobre si (por exemplo, informações sobre a sua atividade anterior neste serviço e outros sites ou aplicações) ou utilizadores semelhantes. Isto é então utilizado para criar ou melhorar um perfil sobre si (que pode incluir possíveis interesses e aspetos pessoais). O seu perfil pode ser utilizado (também mais tarde) para apresentar publicidade que pareça mais relevante com base nos seus possíveis interesses, por esta e outras entidades." },
      4: { name: "Utilizar perfis para selecionar publicidade personalizada", description: "A publicidade que lhe é apresentada neste serviço pode basear-se nos seus perfis de publicidade, que podem refletir a sua atividade neste serviço ou noutros sites ou aplicações (como os formulários que envia, os conteúdos que visualiza), possíveis interesses e aspetos pessoais." },
      5: { name: "Criar perfis para personalizar conteúdos", description: "As informações sobre a sua atividade neste serviço (por exemplo, formulários que envia, conteúdos não publicitários que visualiza) podem ser armazenadas e combinadas com outras informações sobre si (tais como informações sobre a sua atividade anterior neste serviço ou noutros sites ou aplicações) ou utilizadores semelhantes. Isto é então utilizado para criar ou melhorar um perfil sobre si (que pode incluir, por exemplo, possíveis interesses e aspetos pessoais). O seu perfil pode ser utilizado (também mais tarde) para apresentar conteúdos que pareçam mais relevantes com base nos seus possíveis interesses, como por exemplo, adaptando a ordem pela qual os conteúdos lhe são apresentados, para que seja ainda mais fácil para si encontrar conteúdos que correspondam aos seus interesses." },
      6: { name: "Utilizar perfis para selecionar conteúdos personalizados", description: "Os conteúdos, que lhe são apresentados neste serviço, podem basear-se nos seus perfis de personalização de conteúdos, que podem refletir a sua atividade neste ou noutros serviços (por exemplo, os formulários que envia, os conteúdos que visualiza), possíveis interesses e aspetos pessoais. Isto pode, por exemplo, ser utilizado para adaptar a ordem pela qual os conteúdos lhe são apresentados, para que lhe seja ainda mais fácil encontrar conteúdos (não publicitários) que correspondam aos seus interesses." },
      7: { name: "Medir o desempenho da publicidade", description: "As informações relativas à publicidade que lhe é apresentada e à forma como interage com a mesma podem ser utilizadas para determinar quão bem um anúncio funcionou para si ou para outros utilizadores e se os objetivos da publicidade foram alcançados. Por exemplo, se viu um anúncio, se clicou nele, se esse anúncio o levou a comprar um produto ou a visitar um site, etc. Isto é muito útil para compreender a relevância das campanhas publicitárias." },
      8: { name: "Medir o desempenho dos conteúdos", description: "As informações relativas a que conteúdos lhe são apresentados e à forma como interage com os mesmos podem ser utilizadas para determinar se os conteúdos (não publicitários), por exemplo, chegaram ao público-alvo e corresponderam aos respetivos interesses. Por exemplo, se leu um artigo, viu um vídeo, ouviu um podcast ou viu uma descrição de um produto, quanto tempo passou neste serviço e nas páginas Web que visita, etc. Isto é muito útil para compreender a relevância dos conteúdos (não publicitários) que lhe são mostrados." },
      9: { name: "Compreender os públicos através de estatísticas ou combinações de dados de diferentes fontes", description: "Os relatórios podem ser gerados com base na combinação de conjuntos de dados (como perfis de utilizadores, estatísticas, pesquisa de mercado, dados analíticos) relativos às suas interações e às de outros utilizadores com conteúdos publicitários ou (não publicitários) para identificar características comuns (por exemplo, para determinar que públicos-alvo são mais recetivos a uma campanha publicitária ou a determinados conteúdos)." },
      10: { name: "Desenvolver e melhorar serviços", description: "As informações sobre a sua atividade neste serviço, como a sua interação com anúncios ou conteúdos, podem ser muito úteis para melhorar produtos e serviços e para desenvolver novos produtos e serviços com base nas interações do utilizador, o tipo de público, etc. Esta finalidade específica não inclui o desenvolvimento ou melhoria de perfis e identificadores de utilizadores." },
      11: { name: "Utilizar dados limitados para selecionar conteúdos", description: "Os conteúdos que lhe são apresentados neste serviço podem basear-se em dados limitados, tais como o site ou aplicação que está a utilizar, a sua localização não precisa, o seu tipo de dispositivo ou com que conteúdo está (ou esteve) a interagir (por exemplo, para limitar o número de vezes que um vídeo ou um artigo lhe são apresentados)." },
    },
    specialPurposes: {
      1: { name: "Garantir a segurança, evitar e detectar a fraude, e corrigir erros", description: "Os seus dados podem ser utilizados para monitorizar e prevenir atividades incomuns e possivelmente fraudulentas (por exemplo, no que se refere à publicidade, cliques em anúncios por “bots”) e garantir que os sistemas e processos funcionam de forma adequada e segura. Também podem ser utilizados para corrigir quaisquer problemas que o utilizador, o editor ou o anunciante possam encontrar no âmbito da disponibilização de conteúdos e anúncios e na sua interação com os mesmos." },
      2: { name: "Disponibilizar e apresentar publicidade e conteúdos", description: "São utilizadas determinadas informações (como um endereço IP ou capacidades do dispositivo) para garantir a compatibilidade técnica do conteúdo ou da publicidade e para facilitar a transmissão do conteúdo ou anúncio para o seu dispositivo." },
      3: { name: "Guardar e comunicar opções de privacidade", description: "As escolhas que faz relativamente às finalidades e entidades incluídas neste aviso são guardadas e disponibilizadas a essas entidades, sob a forma de sinais digitais (como, por exemplo, uma cadeia de caracteres). Isto é necessário para permitir que este serviço e essas entidades respeitem essas escolhas." },
    },
    features: {
      1: { name: "Fazer corresponder e combinar dados de outras fontes de dados", description: "As informações sobre a sua atividade neste serviço podem ser comparadas e combinadas com outras informações relacionadas consigo e provenientes de várias fontes (por exemplo, a sua atividade num serviço online separado, a sua utilização de um cartão de fidelização na loja ou as suas respostas a um inquérito), para apoiar as finalidades explicadas neste aviso." },
      2: { name: "Ligar dispositivos diferentes", description: "Para apoiar as finalidades explicadas neste aviso, o seu dispositivo pode ser considerado como provavelmente ligado a outros dispositivos que lhe pertencem ou ao seu agregado familiar (por exemplo, porque tem sessão iniciada no mesmo serviço no telefone e no computador, ou porque pode usar a mesma ligação à Internet em ambos os dispositivos)." },
      3: { name: "Identificar dispositivos com base em informações transmitidas automaticamente", description: "O seu dispositivo pode ser distinguido de outros dispositivos com base nas informações que envia automaticamente ao aceder à Internet (por exemplo, o endereço IP da sua ligação à Internet ou o tipo de navegador que está a utilizar) para apoiar as finalidades expostas neste aviso." },
    },
    specialFeatures: {
      1: { name: "Utilizar dados de geolocalização precisos", description: "Com a sua aceitação, a sua localização precisa (num raio inferior a 500 metros) pode ser utilizada para apoiar as finalidades explicadas neste aviso." },
      2: { name: "Identificar dispositivos com base em informações solicitadas ativamente", description: "Com a sua aceitação, determinadas características específicas do seu dispositivo podem ser solicitadas e utilizadas para o distinguir de outros dispositivos (como os tipos de letra ou plug-ins instalados, a resolução do seu ecrã) para apoiar as finalidades explicadas neste aviso." },
    },
  },
  es: {
    purposes: {
      1: { name: "Almacenar la información en un dispositivo y/o acceder a ella", description: "Las cookies, los identificadores de dispositivos o los identificadores online de similares características (p. ej., los identificadores basados en inicio de sesión, los identificadores asignados aleatoriamente, los identificadores basados en la red), junto con otra información (p. ej., la información y el tipo del navegador, el idioma, el tamaño de la pantalla, las tecnologías compatibles, etc.), pueden almacenarse o leerse en tu dispositivo a fin de reconocerlo siempre que se conecte a una aplicación o a una página web para una o varias de los finalidades que se recogen en el presente texto." },
      2: { name: "Uso de datos limitados para seleccionar anuncios básicos", description: "La publicidad que se presenta en este servicio puede basarse en datos limitados, tales como la página web o la aplicación que esté utilizando, tu ubicación no precisa, el tipo de dispositivo o el contenido con el que está interactuando (o con el que ha interactuado) (por ejemplo, para limitar el número de veces que se  presenta un anuncio concreto)." },
      3: { name: "Crear perfiles para publicidad personalizada", description: "La información sobre tu actividad en este servicio (por ejemplo, los formularios que rellenes, el contenido que estás consumiendo) puede almacenarse y combinarse con otra información que se tenga sobre tu persona o sobre usuarios similares(por ejemplo, información sobre tu actividad previa en este servicio y en otras páginas web o aplicaciones). Posteriormente, esto se utilizará para crear o mejorar un perfil sobre tu persona (que podría incluir posibles intereses y aspectos personales). Tu perfil puede utilizarse (también en un momento posterior) para mostrarte publicidad que pueda parecerte más relevante en función de tus posibles intereses, ya sea por parte nuestra o de terceros." },
      4: { name: "Utilizar perfiles para seleccionar la publicidad personalizada", description: "La publicidad presentada en este servicio puede basarse en tus perfiles publicitarios, que pueden reflejar tuactividad en este servicio, en otras páginas web o aplicaciones (tales como los formularios con los que interactuas o el contenido que visualizas), tus posibles intereses y los aspectos personales." },
      5: { name: "Crear un perfil para personalizar el contenido", description: "La información sobre tu actividad en este servicio (por ejemplo, los formularios con los que interactuas  o el contenido no publicitario que visualizas) puede almacenarse y combinarse con otra información relativa a tu persona (por ejemplo, tu actividad pasada en este servicio o en otras páginas web o aplicaciones) o sobre otros usuarios de similares características. Posteriormente, esto se utiliza para la creación o la mejora de tu perfil (que podría incluir, por ejemplo, tus posibles intereses y aspectos personales). Tu perfil se puede utilizar (también en el futuro) para presentar aquel contenido que parezca más relevante en función de tus posibles intereses; por ejemplo, adaptando el orden en el que se muestra el contenido para que sea aún más sencillo encontrar el que coincida con tus intereses." },
      6: { name: "Uso de perfiles para la selección de contenido personalizado", description: "El contenido que se te presenta en este servicio puede basarse en un perfil de personalización de contenido, lo que puede reflejar tu actividad en este u otros servicios (por ejemplo, los formularios que envías o el contenido que visualizas), tus posibles intereses y aspectos personales. Un ejemplo de lo anterior sería la adaptación del orden en el que se te presenta el contenido, para que así te resulte más sencillo encontrar el contenido (no publicitario) que coincida con tus intereses." },
      7: { name: "Medir el rendimiento de la publicidad", description: "La información sobre qué publicidad se te presenta y sobre la forma en que interactúas con ella puede utilizarse para determinar lo bien que ha funcionado un anuncio en tu caso o en el de otros usuarios y si se han alcanzado los objetivos publicitarios. Por ejemplo, si has visualizado un anuncio, si has hecho clic sobre el mismo, si eso te ha llevado posteriormente a comprar un producto o a visitar una página web, etc. Esto resulta muy útil para comprender la relevancia de las campañas publicitarias." },
      8: { name: "Medir el rendimiento del contenido", description: "La información sobre qué contenido se te presenta y sobre la forma en que interactúas con él puede utilizarse para determinar, por ejemplo, si el contenido (no publicitario) ha llegado a su público previsto y ha coincidido con sus intereses.  Por ejemplo, si hasleído un artículo, si has visualizado un vídeo, si has escuchado un “pódcast” o si has consultado la descripción de un producto, cuánto tiempo has pasado en esos servicios y en las páginas web que has visitado, etc. Esto resulta muy útil para comprender la relevancia del contenido (no publicitario) que se te muestra." },
      9: { name: "Comprender al público a través de estadísticas o a través de la combinación de datos procedentes de diferentes fuentes", description: "Se pueden generar informes basados en la combinación de conjuntos de datos (como perfiles de usuario, estadísticas, estudios de mercado, datos analíticos) respecto a tus interacciones y las de otros usuarios con el contenido publicitario (o no publicitario) para identificar las características comunes (por ejemplo, para determinar qué público objetivo es más receptivo a una campaña publicitaria o a ciertos contenidos)." },
      10: { name: "Desarrollo y mejora de los servicios", description: "La información sobre tu actividad en este servicio, como tu interacción con los anuncios o con el contenido, puede resultar muy útil para mejorar productos y  servicios, así como para crear otros nuevos en base a las interacciones de los usuarios, el tipo de audiencia, etc. Esta finalidad específica no incluye el desarrollo ni la mejora de los perfiles de usuario y de identificadores." },
      11: { name: "Uso de datos limitados con el objetivo de seleccionar el contenido", description: "El contenido que se presenta en este servicio puede basarse en datos limitados,  como por ejemplo la página web o la aplicación que esté utilizando, tu ubicación no precisa, el tipo de dispositivo o el contenido con el que estás interactuando (o con el que has interactuado) (por ejemplo, para limitar el número de veces que se te presenta un vídeo o un artículo en concreto)." },
    },
    specialPurposes: {
      1: { name: "Garantizar la seguridad, evitar y detectar fraudes, y eliminar fallos", description: "Tus datos pueden utilizarse para supervisar y evitar las actividades inusuales y potencialmente fraudulentas (por ejemplo, en relación con la publicidad, o con actividad realizada por bots), así como para asegurar que los sistemas y los procesos funcionen de forma correcta y segura. Asimismo, se puede utilizar para corregir cualquier problema que tú, el editor/medio de comunicación o el anunciante podáis encontraros a la hora de la entrega del contenido y los anuncios, así como en tu interacción con ellos." },
      2: { name: "Ofrecer y presentar publicidad y contenido", description: "Cierta información (como una dirección IP o las capacidades del dispositivo) se utiliza para garantizar la compatibilidad técnica del contenido o de la publicidad, así como para facilitar la transmisión del contenido o del anuncio a tu dispositivo." },
      3: { name: "Guardar y comunicar las preferencias de privacidad", description: "Las decisiones que tome con respecto a las finalidades y las entidades enumeradas en este aviso se guardan y se ponen a disposición de dichas entidades en forma de señales digitales (por ejemplo, en forma de cadena de caracteres). Esto es necesario para permitir que tanto este servicio como las entidades respeten dichas preferencias." },
    },
    features: {
      1: { name: "Cotejo y combinación de datos procedentes de otras fuentes de información", description: "La información en relación con tu actividad en este servicio puede cotejarse y combinarse con otra información sobre tu persona procedente de diversas fuentes (por ejemplo, tu actividad en un servicio en línea independiente, tu uso de una tarjeta de fidelización en la tienda o tus respuestas a una encuesta) en apoyo de los fines que se explican en este documento." },
      2: { name: "Vincular diferentes dispositivos", description: "En apoyo de las finalidades que se explican en este documento, tú dispositivo podría considerarse como vinculado a otros dispositivos que te pertenezcan o sean de tu hogar(por ejemplo, porque ha iniciado sesión en el mismo servicio tanto desde tu teléfono como desde tu ordenador, o porque podrías haber utilizado la misma conexión a Internet en ambos dispositivos)." },
      3: { name: "Identificación de dispositivos en función de la información transmitida de forma automática", description: "Tu dispositivo podría distinguirse de otros en función de la información que envía de forma automática al acceder a Internet (por ejemplo, la dirección IP de tu conexión a Internet o el tipo de navegador que estás utilizando) en apoyo de los fines que se exponen en este documento." },
    },
    specialFeatures: {
      1: { name: "Utilizar datos de localización geográfica precisa", description: "Al contar con tu aprobación, tu ubicación exacta (dentro de un radio inferior a 500 metros) podrá utilizarse para apoyar las finalidades que se explican en este documento." },
      2: { name: "Identificar los dispositivos en función de la información solicitada activamente", description: "Con tu aceptación, se pueden solicitar y utilizar ciertas características específicas de tu dispositivo para distinguirlo de otros (por ejemplo, las fuentes o complementos instalados y la resolución de su pantalla) en apoyo de las finalidades que se explican en este documento." },
    },
  },
  sv: {
    purposes: {
      1: { name: "Lagra och/eller få åtkomst till information på en enhet", description: "Cookies, enhets- eller liknande onlineidentifierare (t.ex. inloggningsbaserade identifierare, slumpmässigt tilldelade identifierare, nätverksbaserade identifierare) tillsammans med annan information (t.ex. typ av webbläsare och information, språk, skärmstorlek, teknik som stöds osv.) kan lagras eller läsas på din enhet så att din enhet blir igenkänd varje gång den ansluter till en app eller till en webbplats, för ett eller flera av de ändamål som beskrivs här." },
      2: { name: "Använda begränsade data för att välja reklam", description: "Reklam som presenteras för dig i den här tjänsten kan baseras på begränsade data, såsom webbplatsen eller appen du använder, din icke-exakta plats, din enhetstyp eller det innehåll du interagerar med (till exempel för att begränsa antalet gånger en annons visas för dig)." },
      3: { name: "Skapa profiler för personaliserad reklam", description: "Information om din aktivitet i den här tjänsten (t.ex. formulär du skickar in, innehåll du tittar på) kan lagras och kombineras med annan information om dig (t.ex. information från din tidigare aktivitet i den här tjänsten och på andra webbplatser eller appar) eller liknande användare. Informationen används sedan för att skapa eller förbättra en profil om dig (som kan omfatta möjliga intressen och surfvanor). Denna och andra enheter kan (även senare) använda din profil för att visa reklam som verkar mer relevant baserat på dina eventuella intressen." },
      4: { name: "Använda profiler för att välja personaliserad reklam", description: "Reklam som presenteras för dig på denna tjänst kan baseras på dina annonsprofiler, vilket kan återspegla din aktivitet i denna tjänst eller på andra webbplatser eller appar (som de formulär du skickar in, innehåll du tittar på), möjliga intressen och surfvanor." },
      5: { name: "Skapa profiler för att personaliserad innehåll", description: "Information om din aktivitet i den här tjänsten (t.ex. formulär du skickar in, annat än reklaminnehåll som du tittar på) kan lagras och kombineras med annan information om dig (t.ex. information från din tidigare aktivitet i den här tjänsten eller på andra webbplatser eller appar) eller liknande användare. Informationen används sedan för att skapa eller förbättra en profil om dig (som till exempel kan omfatta tänkbara intressen och surfvanor). Din profil kan (även senare) användas för att visa innehåll som verkar mer relevant baserat på dina tänkbara intressen, till exempel genom att anpassa en ordning för hur innehåll visas för dig, så att det blir ännu enklare för dig att hitta innehåll som matchar dina intressen." },
      6: { name: "Använda profiler för att välja personaliserad innehåll", description: "Innehåll som visas för dig på denna tjänst kan baseras på dina profiler för innehållsanpassning, vilket kan återspegla din aktivitet i denna eller andra tjänster (till exempel de formulär du skickar in, innehåll du tittar på), möjliga intressen och surfbeteenden. Profilerna kan användas bland annat för att anpassa ordningen för hur innehåll visas för dig, så att det är ännu lättare för dig att hitta innehåll (annat än reklam) som matchar dina intressen." },
      7: { name: "Mäta reklamprestanda", description: "Information om vilken reklam som visas för dig och hur du interagerar med den kan användas för att avgöra hur bra en annons har fungerat för dig eller andra användare och om målen för reklamen uppnåddes. Till exempel huruvida du såg en annons, om du klickade på den, om det fick dig att köpa en produkt eller besöka en webbplats osv. Detta är till stor hjälp för att förstå reklamkampanjernas relevans." },
      8: { name: "Mäta innehållsprestanda", description: "Information om vilket innehåll som visas för dig och hur du interagerar med det kan användas för att avgöra om innehållet (annat än reklam) t.ex. nådde sin avsedda målgrupp och matchade dina intressen. Till exempel om du läser en artikel, tittar på en video, lyssnar på en poddsändning eller tittar på en produktbeskrivning, hur lång tid du tillbringade i den här tjänsten och de webbsidor du besöker osv. Detta är till stor hjälp för att förstå relevansen av innehåll (annat än reklam) som visas för dig." },
      9: { name: "Förstå målgrupper genom statistik eller kombinationer av data från olika källor", description: "Rapporter kan genereras baserat på kombinationen av datauppsättningar (som användarprofiler, statistik, marknadsundersökningar, analysdata) avseende dina och andra användares interaktioner med reklaminnehåll eller annat än reklaminnehåll, för att identifiera vanliga egenskaper (till exempel för att bestämma vilka målgrupper som är mer mottagliga för en annonskampanj eller för visst innehåll)." },
      10: { name: "Utveckla och förbättra tjänster", description: "Information om din aktivitet i denna tjänst, såsom din interaktion med annonser eller innehåll, kan vara till stor hjälp för att förbättra produkter och tjänster och för att skapa nya produkter och tjänster baserat på användarinteraktioner, typ av publik osv. Detta specifika ändamål omfattar inte utveckling eller förbättring av användarprofiler och identifierare." },
      11: { name: "Använda begränsade data för att välja innehåll", description: "Innehåll som visas för dig på den här tjänsten kan baseras på begränsade data, såsom webbplatsen eller appen du använder, din exakta plats, din enhetstyp eller vilket innehåll du interagerar (eller har interagerat) med (till exempel för att begränsa antalet gånger en annons visas för dig)." },
    },
    specialPurposes: {
      1: { name: "Säkerställa säkerhet, förhindra och upptäcka bedrägerier samt åtgärda fel", description: "Dina uppgifter kan användas för att övervaka och förhindra ovanliga och eventuellt bedrägliga aktiviteter (t.ex. avseende reklam, annonsklick från robotar) och säkerställa att system och processer fungerar korrekt och säkert. De kan också användas för att korrigera eventuella problem som du, utgivaren eller annonsören kan stöta på i leveransen av innehåll och annonser och i din interaktion med dem." },
      2: { name: "Leverera och visa reklam och innehåll", description: "Viss information (t.ex. en IP-adress eller en enhets kapacitet) används för att säkerställa innehållets eller reklamens tekniska kompatibilitet och för att underlätta överföringen av innehållet eller annonsen till din enhet." },
      3: { name: "Spara och meddela dina integritetsval", description: "De inställningar du gör för de ändamål och enheter som anges i detta meddelande sparas och görs tillgängliga för de aktuella enheterna i form av digitala signaler (t.ex. en teckensträng). Detta är nödvändigt för att leverera denna tjänst och säkerställa att de aktuella enheterna respekterar dina val." },
    },
    features: {
      1: { name: "Matchar och kombinerar data från andra datakällor", description: "Information om din aktivitet på den här tjänsten kan matchas och kombineras med annan information om dig och kommer från olika källor (till exempel din aktivitet på en separat onlinetjänst, din användning av ett lojalitetskort i butik eller dina svar på en undersökning), till stöd för de ändamål som förklaras i detta meddelande." },
      2: { name: "Länka olika enheter", description: "Till stöd för de ändamål som beskrivs i detta meddelande kan din enhet anses som att den sannolikt är kopplad till andra enheter som tillhör dig eller ditt hushåll (till exempel för att du är inloggad i samma tjänst på både din telefon och din dator, eller för att du kan använda samma internetanslutning på båda enheterna)." },
      3: { name: "Identifierar enheter baserat på information som överförs automatiskt", description: "Din enhet kan särskiljas från andra enheter baserat på information som funktionen automatiskt skickar vid åtkomst till internet (till exempel IP-adressen för din internetanslutning eller vilken typ av webbläsare du använder) till stöd för de ändamål som anges i detta meddelande." },
    },
    specialFeatures: {
      1: { name: "Använda exakta uppgifter om geografisk positionering", description: "Med ditt samtycke kan din exakta plats (inom en radie på mindre än 500 meter) användas för att stödja de ändamål som beskrivs i detta meddelande." },
      2: { name: "Identifiera enheter baserat på information som aktivt begärs", description: "Med ditt samtycke kan vissa egenskaper som är specifika för din enhet begäras och användas för att skilja den från andra enheter (t.ex. installerade teckensnitt eller plugin-program, upplösningen på din skärm) till stöd för de ändamål som beskrivs i detta meddelande." },
    },
  },
};
